// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUTVM8zDDqcaex7EQ0VQLDIsrXlHAoQXk',
    appId: '1:62200588877:ios:0c0e584988acc900648a04',
    messagingSenderId: '62200588877',
    projectId: 'mediguide-1d550',
    storageBucket: 'mediguide-1d550.firebasestorage.app',
    iosBundleId: 'com.example.mediguid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUTVM8zDDqcaex7EQ0VQLDIsrXlHAoQXk',
    appId: '1:62200588877:ios:0c0e584988acc900648a04',
    messagingSenderId: '62200588877',
    projectId: 'mediguide-1d550',
    storageBucket: 'mediguide-1d550.firebasestorage.app',
    iosBundleId: 'com.example.mediguid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA94tbhW8Ubw6Tum2pdx_IS5s7ud34lc2k',
    appId: '1:62200588877:web:0810617be4f5e823648a04',
    messagingSenderId: '62200588877',
    projectId: 'mediguide-1d550',
    authDomain: 'mediguide-1d550.firebaseapp.com',
    storageBucket: 'mediguide-1d550.firebasestorage.app',
    measurementId: 'G-ZP3Y78NXBN',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94tbhW8Ubw6Tum2pdx_IS5s7ud34lc2k',
    appId: '1:62200588877:web:0810617be4f5e823648a04',
    messagingSenderId: '62200588877',
    projectId: 'mediguide-1d550',
    authDomain: 'mediguide-1d550.firebaseapp.com',
    storageBucket: 'mediguide-1d550.firebasestorage.app',
    measurementId: 'G-ZP3Y78NXBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAObLGHSNgx_ccIftU8hUMbb-MvgxAKD9g',
    appId: '1:62200588877:android:df93cb75b6a68142648a04',
    messagingSenderId: '62200588877',
    projectId: 'mediguide-1d550',
    storageBucket: 'mediguide-1d550.firebasestorage.app',
  );
}
